### PR TITLE
EFS support

### PR DESCRIPTION
**Pull request by michaelwittig**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
wait for cfn-lint update

**Comment by michaelwittig** [comment]
test

**Review by andreaswittig — APPROVED** [review]
👍

**Review by andreaswittig — APPROVED** [review]

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
test

**Comment by andreaswittig** [comment]
For backwards compatibility it might be necessary to set `PlatformVersion` for `AWS::ECS::Service`. At least, that was an issue I had when activating EFS for an ECS Service with Terraform.

**Review by andreaswittig — APPROVED** [review]
👍

**Comment by michaelwittig** [comment]
test

**Pull request merged**
