### PR TITLE
Add missing Policies entries for AppEnvironment4Secret and AppEnviron…

### PR DESCRIPTION
**Pull request by tjsnell**
Add missing Policies entries for AppEnvironment4Secret and AppEnvironment5Secret. Fixed a typo in AppEnvironment5Secret description

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @tjsnell Thanks for your PR. Would it be possible to focus on the "missing Policies entries" besides the other changes to the template? Your editor might modified the YAML automatically?

**Comment by tjsnell** [comment]
Sure, I'll make the changes and submit. Drop the misspelling change too?  The version changes were for me locally, should've dropped those anyway.

**Comment by tjsnell** [comment]
Wow, I didn't check the diff. Should've been very small. Idea decided to reformat a bunch and there's other changes that I somehow got in there. I'm going to close this one and submit a clean PR. Sorry about that! Rushed it out this morning during a deploy.

**Comment by michaelwittig** [comment]
@tjsnell no worries. Thanks for doing the changes in #47

**Pull request closed without merging**
