### PR TITLE
Adding app container envs + ECS exec command

### PR DESCRIPTION
**Pull request by andreaswittig**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreaswittig** [comment]
test

**Review by michaelwittig — APPROVED** [review]

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Pull request merged**
