### PR TITLE
Adding options for CPU architecture and OS

### PR DESCRIPTION
**Pull request by andreaswittig**
Adding options for CPU architecture and OS. Mostly, to allow launching Fargate tasks with ARM/Gravition processors.

### CODE REVIEW

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Review by michaelwittig — APPROVED** [review]

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Review by michaelwittig — APPROVED** [review]

**Comment by andreaswittig** [comment]
test

**Pull request merged**
